### ISSUE TITLE
Won't compile on Netlify

### ISSUE THREAD

**Issue by BobWalsh** [oktadeveloper/okta-vuepress-authentication-personalization-example#1]
Hi,
Worked through the tutorial, then cloned this repo and made the Configuration changes - and it's working at localhost:8080.

But it won't compile a build on Netlify:
```
...
2:00:02 PM: Rendering page: /implicit/callback/
2:00:02 PM: error Error rendering /implicit/callback/: false
2:00:02 PM: undefined
2:00:02 PM: ReferenceError: window is not defined
2:00:02 PM:     at Object.<anonymous> (node_modules/@okta/okta-vue/dist/okta-vue.js:1:222)
2:00:02 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:00:02 PM:     at Module.<anonymous> (server-bundle.js:2104:16)
2:00:02 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:00:02 PM:     at Object.<anonymous> (server-bundle.js:1480:18)
2:00:02 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:00:02 PM:     at server-bundle.js:118:18
2:00:02 PM:     at Object.<anonymous> (server-bundle.js:121:10)
2:00:02 PM:     at evaluateModule (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:9303:21)
2:00:02 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.dev.js:9361:18
2:00:02 PM:     at new Promise (<anonymous>)
2:00:02 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.dev.js:9353:14
2:00:02 PM:     at Object.renderToString (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:9529:9)
2:00:02 PM:     at Build.renderPage (/opt/build/repo/node_modules/@vuepress/core/lib/node/build/index.js:156:34)
2:00:02 PM:     at Build.render (/opt/build/repo/node_modules/@vuepress/core/lib/node/build/index.js:94:33)
2:00:02 PM: Skipping functions preparation step: no functions directory set
2:00:02 PM: Caching artifacts
2:00:02 PM: Started saving node modules
...
```
I like Okta, and would like to use this service. But need to get this deployable on Netlify.

**Comment by BobWalsh** [comment]
ote
